package com.example.postapi

import com.example.postapi.config.CorsConfig
import com.example.postapi.config.DatabaseFactory
import com.example.postapi.config.JsonMapper
import com.example.postapi.handler.AdminHandler
import com.example.postapi.handler.DocsHandler
import com.example.postapi.handler.HealthHandler
import com.example.postapi.handler.OpenApiHandler
import com.example.postapi.handler.PostHandler
import com.example.postapi.handler.RateLimitHandler
import com.example.postapi.handler.RequestLoggingHandler
import com.example.postapi.repository.PostRepository
import com.example.postapi.service.PostService
import com.example.postapi.batch.CleanupJob
import io.muserver.MuServer
import io.muserver.MuServerBuilder
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import okhttp3.Response
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.nio.file.Paths
import javax.sql.DataSource

/**
 * 运维端点集成测试 — 覆盖 OpenAPI spec, health liveness/readiness, RateLimit, CORS 白名单
 *
 * 跟 PostHandlerIntegrationTest 用同样的 OkHttp + H2 in-memory 模式，但只注册运维端点
 * 简化断言（CORS header, 429, JSON status 等）。
 */
class OperationalEndpointsTest {

    private lateinit var server: MuServer
    private lateinit var dataSource: DataSource
    private lateinit var client: OkHttpClient
    private lateinit var baseUri: String

    @BeforeEach
    fun setUp() {
        val h2Url = "jdbc:h2:mem:ops-${System.nanoTime()};DB_CLOSE_DELAY=-1"
        dataSource = DatabaseFactory.create(url = h2Url, user = "sa", password = "")
        initializeH2Schema(dataSource)

        val postRepository = PostRepository(dataSource)
        val postService = PostService(postRepository)
        val postHandler = PostHandler(postService)
        val cleanupJob = CleanupJob(postRepository)
        val adminHandler = AdminHandler(cleanupJob)
        val healthHandler = HealthHandler(dataSource)

        val builder = MuServerBuilder.httpServer().withHttpPort(0)
        builder.addHandler(CorsConfig.create())
        OpenApiHandler.register().forEach { builder.addHandler(it) }
        healthHandler.register().forEach { builder.addHandler(it) }
        DocsHandler.register().forEach { builder.addHandler(it) }
        val allRoutes = postHandler.register() + adminHandler.register()
        RequestLoggingHandler.wrapAll(allRoutes).forEach { builder.addHandler(it) }
        server = builder.start()
        baseUri = "http://localhost:${server.uri().port}"
        client = OkHttpClient.Builder().build()
    }

    private fun initializeH2Schema(ds: DataSource) {
        val ddl = """
            CREATE TABLE IF NOT EXISTS posts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(200) NOT NULL,
                content CLOB NOT NULL,
                author_name VARCHAR(50) NOT NULL,
                cover_image VARCHAR(500),
                view_count BIGINT DEFAULT 0,
                like_count BIGINT DEFAULT 0,
                is_published BOOLEAN DEFAULT FALSE,
                is_deleted BOOLEAN DEFAULT FALSE,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
        """.trimIndent()
        ds.connection.use { it.createStatement().use { stmt -> stmt.execute(ddl) } }
    }

    @AfterEach
    fun tearDown() {
        server.stop()
        (dataSource as? com.zaxxer.hikari.HikariDataSource)?.close()
        client.dispatcher.executorService.shutdown()
        client.connectionPool.evictAll()
    }

    private fun get(path: String): Response = client.newCall(
        Request.Builder().url("$baseUri$path").get().build()
    ).execute()

    // ============ /openapi.json ============

    @Test
    fun `openapi json - 200 and serves spec with correct content type`() {
        val resp = get("/openapi.json")
        resp.use {
            assertThat(it.code).isEqualTo(200)
            assertThat(it.header("Content-Type")).contains("application/json")
            val body = it.body?.string() ?: ""
            assertThat(body).contains("\"openapi\"")
            assertThat(body).contains("\"paths\"")
            assertThat(body).contains("/api/posts")
        }
    }

    @Test
    fun `openapi json - CORS allow any origin (public spec)`() {
        val req = Request.Builder()
            .url("$baseUri/openapi.json")
            .header("Origin", "https://example.com")
            .get()
            .build()
        val resp = client.newCall(req).execute()
        resp.use {
            assertThat(it.code).isEqualTo(200)
            assertThat(it.header("Access-Control-Allow-Origin")).isEqualTo("https://example.com")
            assertThat(it.header("Cache-Control")).isEqualTo("public, max-age=300")
        }
    }

    @Test
    fun `openapi json - OPTIONS preflight returns 204`() {
        val req = Request.Builder()
            .url("$baseUri/openapi.json")
            .method("OPTIONS", null)
            .header("Origin", "https://example.com")
            .header("Access-Control-Request-Method", "GET")
            .build()
        val resp = client.newCall(req).execute()
        resp.use {
            assertThat(it.code).isEqualTo(204)
            assertThat(it.header("Access-Control-Allow-Methods")).contains("GET")
        }
    }

    // ============ /health ============

    @Test
    fun `health - 200 ok always`() {
        val resp = get("/health")
        resp.use {
            assertThat(it.code).isEqualTo(200)
            assertThat(it.header("Content-Type")).contains("application/json")
            val body = it.body?.string() ?: ""
            assertThat(body).contains("\"status\":\"ok\"")
        }
    }

    @Test
    fun `health ready - 200 ok when DB up`() {
        val resp = get("/health/ready")
        resp.use {
            assertThat(it.code).isEqualTo(200)
            val body = it.body?.string() ?: ""
            assertThat(body).contains("\"db\":\"up\"")
        }
    }

    // ============ RateLimit ============

    @Test
    fun `rate limit - allows first N requests then returns 429`() {
        // 独立 server 用低 limit (3/sec) 测快速触限
        val rateLimit = RateLimitHandler(requestsPerSecond = 3)
        val postRepository = PostRepository(dataSource)
        val postService = PostService(postRepository)
        val postHandler = PostHandler(postService)
        val cleanupJob = CleanupJob(postRepository)
        val adminHandler = AdminHandler(cleanupJob)

        val builder = io.muserver.MuServerBuilder.httpServer().withHttpPort(0)
        builder.addHandler(rateLimit)
        val routes = postHandler.register() + adminHandler.register()
        routes.forEach { builder.addHandler(it) }
        val s = builder.start()
        val uri = "http://localhost:${s.uri().port}"
        val localClient = OkHttpClient.Builder().build()

        try {
            // 先 create 一篇 post，然后 like 多次
            localClient.newCall(
                Request.Builder().url("$uri/api/posts")
                    .post("""{"title":"RL","content":"X","authorName":"A"}""".toRequestBody(jsonMt))
                    .build()
            ).execute().use { assertThat(it.code).isEqualTo(200) }

            // POST /api/posts/1/like × 5 — limit 是 3，应该至少收到一个 429
            var got429 = false
            for (i in 1..5) {
                val resp = localClient.newCall(
                    Request.Builder().url("$uri/api/posts/1/like").post("".toRequestBody(jsonMt)).build()
                ).execute()
                resp.use {
                    if (it.code == 429) {
                        got429 = true
                        assertThat(it.header("Retry-After")).isEqualTo("1")
                    }
                }
            }
            assertThat(got429).`as`("Should have at least one 429 within burst of 5 against limit 3").isTrue
        } finally {
            s.stop()
            localClient.dispatcher.executorService.shutdown()
            localClient.connectionPool.evictAll()
        }
    }

    @Test
    fun `rate limit - does NOT limit GET paths`() {
        val rateLimit = RateLimitHandler(requestsPerSecond = 2)
        val postRepository = PostRepository(dataSource)
        val postService = PostService(postRepository)
        val postHandler = PostHandler(postService)

        val builder = io.muserver.MuServerBuilder.httpServer().withHttpPort(0)
        builder.addHandler(rateLimit)
        postHandler.register().forEach { builder.addHandler(it) }
        val s = builder.start()
        val uri = "http://localhost:${s.uri().port}"
        val localClient = OkHttpClient.Builder().build()

        try {
            // GET 路径 × 10 — 永远不应该 429
            for (i in 1..10) {
                val resp = localClient.newCall(
                    Request.Builder().url("$uri/api/posts/published?page=0&size=10").get().build()
                ).execute()
                resp.use {
                    assertThat(it.code).isNotEqualTo(429)
                }
            }
        } finally {
            s.stop()
            localClient.dispatcher.executorService.shutdown()
            localClient.connectionPool.evictAll()
        }
    }

    @Test
    fun `rate limit - disabled when env RATE_LIMIT_ENABLED false`() {
        // 用 enabled=false 的 handler，验证即使 burst 也不会 429
        val rateLimit = RateLimitHandler(requestsPerSecond = 1, enabled = false)
        val postRepository = PostRepository(dataSource)
        val postService = PostService(postRepository)
        val postHandler = PostHandler(postService)

        val builder = io.muserver.MuServerBuilder.httpServer().withHttpPort(0)
        builder.addHandler(rateLimit)
        postHandler.register().forEach { builder.addHandler(it) }
        val s = builder.start()
        val uri = "http://localhost:${s.uri().port}"
        val localClient = OkHttpClient.Builder().build()

        try {
            localClient.newCall(
                Request.Builder().url("$uri/api/posts")
                    .post("""{"title":"RLOff","content":"X","authorName":"A"}""".toRequestBody(jsonMt))
                    .build()
            ).execute().use { assertThat(it.code).isEqualTo(200) }

            // 10 次 like — disabled 永远 200
            for (i in 1..10) {
                val resp = localClient.newCall(
                    Request.Builder().url("$uri/api/posts/1/like").post("".toRequestBody(jsonMt)).build()
                ).execute()
                resp.use {
                    assertThat(it.code).isEqualTo(200)
                }
            }
        } finally {
            s.stop()
            localClient.dispatcher.executorService.shutdown()
            localClient.connectionPool.evictAll()
        }
    }

    // ============ CORS 白名单 ============

    @Test
    fun `CORS - allowed origin gets Access-Control-Allow-Origin header`() {
        // 默认白名单包含 http://localhost:5173 (Vite)
        val req = Request.Builder()
            .url("$baseUri/api/posts/published?page=0&size=10")
            .header("Origin", "http://localhost:5173")
            .get()
            .build()
        val resp = client.newCall(req).execute()
        resp.use {
            assertThat(it.header("Access-Control-Allow-Origin")).isEqualTo("http://localhost:5173")
        }
    }

    @Test
    fun `CORS - disallowed origin does NOT get Access-Control-Allow-Origin header`() {
        val req = Request.Builder()
            .url("$baseUri/api/posts/published?page=0&size=10")
            .header("Origin", "https://evil.example.com")
            .get()
            .build()
        val resp = client.newCall(req).execute()
        resp.use {
            // 白名单之外的 origin 不返回 CORS allow 头
            assertThat(it.header("Access-Control-Allow-Origin")).isNull()
        }
    }

    @Test
    fun `docs - GET docs redirects 301 to docs index html`() {
        val noFollowClient = client.newBuilder().followRedirects(false).build()
        val req = Request.Builder().url("$baseUri/docs").get().build()
        val resp = noFollowClient.newCall(req).execute()
        resp.use {
            assertThat(it.code).isEqualTo(301)
            assertThat(it.header("Location")).isEqualTo("/docs/index.html")
        }
        noFollowClient.dispatcher.executorService.shutdown()
        noFollowClient.connectionPool.evictAll()
    }

    @Test
    fun `docs - GET docs index html serves Swagger UI HTML`() {
        val resp = get("/docs/index.html")
        resp.use {
            assertThat(it.code).isEqualTo(200)
            val body = it.body?.string() ?: ""
            assertThat(body).contains("swagger-ui")
            assertThat(body).contains("/openapi.json")
        }
    }

    private val jsonMt = "application/json; charset=utf-8".toMediaType()
}
