package com.example.postapi

import com.example.postapi.batch.CleanupJob
import com.example.postapi.config.DatabaseFactory
import com.example.postapi.config.JsonMapper
import com.example.postapi.dto.ApiResult
import com.example.postapi.handler.AdminHandler
import com.example.postapi.handler.PostHandler
import com.example.postapi.repository.PostRepository
import com.example.postapi.service.PostService
import io.muserver.MuServer
import io.muserver.MuServerBuilder
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import okhttp3.Response
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.nio.file.Paths
import javax.sql.DataSource

/**
 * PostHandler 集成测试 — 替代 Spring MockMvc PostControllerTest
 *
 * 策略：用 OkHttp client 启动真实 mu-server + H2 in-memory DB
 * 覆盖原版 PostControllerTest 9 个 endpoint 的行为（CRUD + 分页 + 搜索 + toggle + like）
 *
 * Threading note：mu-server 2.4.2 的 NettyResponseAdaptor.write(String) 内部自动调
 * httpExchange.block(...) 跨线程同步到 event loop，所以 handler 可以直接在
 * handler executor 线程调 write/status/contentType —— 全部 thread-safe。
 *
 * Schema note：测试用独立 H2-native schema（不用 schema-postgres.sql 那个 PostgreSQL 特定语法的
 * 脚本——H2 不支持 BIGSERIAL/INTERVAL/ON CONFLICT）。改在 initializeH2Schema 内联。
 */
class PostHandlerIntegrationTest {

    private lateinit var server: MuServer
    private lateinit var dataSource: DataSource
    private lateinit var client: OkHttpClient
    private lateinit var baseUri: String

    private val jsonMediaType = "application/json; charset=utf-8".toMediaType()
    private val emptyBody = "".toRequestBody(null)

    @BeforeEach
    fun setUp() {
        // 1. H2 in-memory database
        val h2Url = "jdbc:h2:mem:test-${System.nanoTime()};DB_CLOSE_DELAY=-1"
        dataSource = DatabaseFactory.create(url = h2Url, user = "sa", password = "")
        initializeH2Schema(dataSource)

        // 2. Wire up
        val postRepository = PostRepository(dataSource)
        val postService = PostService(postRepository)
        val postHandler = PostHandler(postService)
        val cleanupJob = CleanupJob(postRepository)
        val adminHandler = AdminHandler(cleanupJob)

        // 3. 启动 mu-server
        val builder = MuServerBuilder.httpServer().withHttpPort(0)
        postHandler.register().forEach { builder.addHandler(it) }
        adminHandler.register().forEach { builder.addHandler(it) }
        server = builder.start()
        val port = server.uri().port
        baseUri = "http://localhost:$port"

        client = OkHttpClient.Builder().build()
    }

    /**
     * H2-native schema（不依赖 PostgreSQL mode）—— 测试专用。
     * 原版 schema-postgres.sql 用 BIGSERIAL / INTERVAL '60 days' / ON CONFLICT，H2 不全支持。
     */
    private fun initializeH2Schema(ds: DataSource) {
        val ddl = """
            CREATE TABLE IF NOT EXISTS posts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(200) NOT NULL,
                content CLOB NOT NULL,
                author_name VARCHAR(50) NOT NULL,
                cover_image VARCHAR(500),
                view_count BIGINT DEFAULT 0,
                like_count BIGINT DEFAULT 0,
                is_published BOOLEAN DEFAULT FALSE,
                is_deleted BOOLEAN DEFAULT FALSE,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE INDEX IF NOT EXISTS idx_posts_title ON posts(title);
            CREATE INDEX IF NOT EXISTS idx_posts_is_published ON posts(is_published);
            CREATE INDEX IF NOT EXISTS idx_posts_is_deleted ON posts(is_deleted);
            CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at);
        """.trimIndent()
        ds.connection.use { conn ->
            conn.createStatement().use { stmt ->
                stmt.execute(ddl)  // 不吞错——让问题立即可见
            }
        }
    }

    @AfterEach
    fun tearDown() {
        server.stop()
        (dataSource as? com.zaxxer.hikari.HikariDataSource)?.close()
        client.dispatcher.executorService.shutdown()
        client.connectionPool.evictAll()
    }

    // ============ OkHttp Helper ============

    private fun get(path: String): Response = client.newCall(
        Request.Builder().url("$baseUri$path").get().build()
    ).execute()

    private fun post(path: String, body: String? = null): Response = client.newCall(
        Request.Builder()
            .url("$baseUri$path")
            .post((body ?: "").toRequestBody(jsonMediaType))
            .build()
    ).execute()

    private fun put(path: String, body: String): Response = client.newCall(
        Request.Builder()
            .url("$baseUri$path")
            .put(body.toRequestBody(jsonMediaType))
            .build()
    ).execute()

    private fun delete(path: String): Response = client.newCall(
        Request.Builder().url("$baseUri$path").delete(emptyBody).build()
    ).execute()

    /** 验证 endpoint 响应是 JSON ApiResult 且 code 符合预期 */
    private fun assertApiResult(resp: Response, expectedCode: Int): ApiResult<*> {
        resp.use {
            assertThat(it.code).`as`("HTTP status").isEqualTo(if (expectedCode >= 400) expectedCode else 200)
            assertThat(it.header("Content-Type")).`as`("Content-Type").contains("application/json")
            val body = it.body?.string() ?: ""
            val result = JsonMapper.readValue<ApiResult<Any>>(body)
            assertThat(result.code).`as`("ApiResult.code").isEqualTo(expectedCode)
            return result
        }
    }

    // ============ 9 个 Endpoint 集成测试 ============

    @Test
    fun `createPost - POST api posts`() {
        val resp = post("/api/posts", """{"title":"New Post","content":"Content","authorName":"Author"}""")
        val result = assertApiResult(resp, 200)
        assertThat(result.data).isNotNull()
    }

    @Test
    fun `updatePost - PUT api posts id`() {
        post("/api/posts", """{"title":"Original","content":"X","authorName":"A"}""")
        val resp = put("/api/posts/1", """{"title":"Updated Title","content":"Updated"}""")
        assertApiResult(resp, 200)
    }

    @Test
    fun `getPostById - GET api posts id`() {
        post("/api/posts", """{"title":"Test","content":"X","authorName":"A"}""")
        val resp = get("/api/posts/1")
        assertApiResult(resp, 200)
    }

    @Test
    fun `getPostNotFound - 404 when id missing`() {
        val resp = get("/api/posts/999999")
        assertApiResult(resp, 404)
    }

    @Test
    fun `deletePost - DELETE api posts id`() {
        post("/api/posts", """{"title":"ToDelete","content":"X","authorName":"A"}""")
        val resp = delete("/api/posts/1")
        assertApiResult(resp, 200)
    }

    @Test
    fun `listPublishedPosts - GET api posts published`() {
        val resp = get("/api/posts/published?page=0&size=10")
        assertApiResult(resp, 200)
    }

    @Test
    fun `listAllPosts - GET api posts all`() {
        val resp = get("/api/posts/all?page=0&size=10")
        assertApiResult(resp, 200)
    }

    @Test
    fun `searchPosts - GET api posts search`() {
        post("/api/posts", """{"title":"SearchablePost","content":"X","authorName":"A"}""")
        val resp = get("/api/posts/search?keyword=Search&page=0&size=10")
        assertApiResult(resp, 200)
    }

    @Test
    fun `togglePublish - POST api posts id toggle-publish`() {
        post("/api/posts", """{"title":"Toggle","content":"X","authorName":"A"}""")
        val resp = post("/api/posts/1/toggle-publish")
        assertApiResult(resp, 200)
    }

    @Test
    fun `likePost - POST api posts id like`() {
        post("/api/posts", """{"title":"Like","content":"X","authorName":"A"}""")
        val resp = post("/api/posts/1/like")
        assertApiResult(resp, 200)
    }

    // ============ Batch Job ============

    @Test
    fun `cleanupJob - POST api admin cleanup-job triggers runNow`() {
        val resp = post("/api/admin/cleanup-job")
        assertApiResult(resp, 200)
    }

    // ============ 单元测试（不依赖 mu-server）==========

    @Test
    fun `ApiResult ok - factory method`() {
        val result = ApiResult.ok("hello")
        assertThat(result.code).isEqualTo(200)
        assertThat(result.message).isEqualTo("success")
        assertThat(result.data).isEqualTo("hello")
    }

    @Test
    fun `ApiResult fail - factory method`() {
        val result = ApiResult.fail<Any>(400, "bad request")
        assertThat(result.code).isEqualTo(400)
        assertThat(result.message).isEqualTo("bad request")
    }

    @Test
    fun `CreatePostRequest init - validates required fields`() {
        var threw = false
        try {
            com.example.postapi.dto.CreatePostRequest("", "c", "a", null)
        } catch (e: IllegalArgumentException) { threw = true }
        assertThat(threw).isTrue
    }

    @Test
    fun `CreatePostRequest init - title length max 200`() {
        var threw = false
        val longTitle = "a".repeat(201)
        try {
            com.example.postapi.dto.CreatePostRequest(longTitle, "c", "a", null)
        } catch (e: IllegalArgumentException) { threw = true }
        assertThat(threw).isTrue
    }

    @Test
    fun `NotFoundException - 404 code`() {
        val ex = com.example.postapi.exception.NotFoundException("not here")
        assertThat(ex.errorCode).isEqualTo(404)
    }
}