-- H2 Schema for Post API (Kotlin + mu-server 2.4.2)
-- 用于 dev / test 环境（jdbc:h2:mem:* URL）
-- 跟 schema-postgres.sql 区别：
--   - BIGSERIAL → BIGINT GENERATED BY DEFAULT AS IDENTITY（H2 不识别 BIGSERIAL）
--   - 没有 INTERVAL / ON CONFLICT 种子（避免 H2 兼容性坑）

CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content CLOB NOT NULL,
    author_name VARCHAR(50) NOT NULL,
    cover_image VARCHAR(500),
    view_count BIGINT DEFAULT 0,
    like_count BIGINT DEFAULT 0,
    is_published BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_posts_title ON posts(title);
CREATE INDEX IF NOT EXISTS idx_posts_is_published ON posts(is_published);
CREATE INDEX IF NOT EXISTS idx_posts_is_deleted ON posts(is_deleted);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at);
