package com.example.postapi.config

import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import org.slf4j.LoggerFactory
import javax.sql.DataSource

/**
 * HikariCP DataSource 单例 — 替代 Spring Boot 自动配置的 spring.datasource
 */
object DatabaseFactory {
    private val log = LoggerFactory.getLogger(DatabaseFactory::class.java)

    /**
     * 创建 DataSource（参数 override 环境变量，用于测试传入 H2 in-memory URL）
     */
    fun create(url: String? = null, user: String? = null, password: String? = null): DataSource {
        val actualUrl = url ?: (System.getenv("DB_URL") ?: "jdbc:postgresql://localhost:5432/testdb")
        val actualUser = user ?: (System.getenv("DB_USER") ?: "postgres")
        val actualPassword = password ?: (System.getenv("DB_PASSWORD") ?: "postgres")

        log.info("Initializing HikariCP DataSource: url={}, user={}", actualUrl, actualUser)

        val config = HikariConfig().apply {
            driverClassName = if (actualUrl.startsWith("jdbc:h2")) "org.h2.Driver" else "org.postgresql.Driver"
            jdbcUrl = actualUrl
            this.username = actualUser
            this.password = actualPassword
            maximumPoolSize = 10
            minimumIdle = 2
            idleTimeout = 30_000
            connectionTimeout = 10_000
            poolName = "post-api-pool"
            isAutoCommit = true
        }
        return HikariDataSource(config)
    }

    fun initializeSchema(ds: DataSource) {
        val isH2 = ds.connection.use { it.metaData.url }.startsWith("jdbc:h2")
        val resourceName = if (isH2) "schema-h2.sql" else "schema-postgres.sql"
        log.info("Initializing database schema from classpath resource: {}", resourceName)
        // Read schema from classpath (packaged into the jar at build time via
        // src/main/resources/). Works in any environment: dev (IDE), Gradle
        // test (classpath includes build/resources/main), and Docker runtime
        // (installDir's lib/*.jar contains the resource).
        var sql = this::class.java.classLoader.getResourceAsStream(resourceName)?.use { stream ->
            stream.bufferedReader().readText()
        } ?: run {
            // Some Gradle test invocations don't add build/resources/main to classpath
            // when running outside of the standard test task. Try the absolute path
            // as a fallback for dev convenience.
            val devPath = java.nio.file.Paths.get("src/main/resources/$resourceName")
            if (java.nio.file.Files.exists(devPath)) {
                java.nio.file.Files.readString(devPath)
            } else {
                error("Schema resource not found on classpath: $resourceName (and dev fallback missing too)")
            }
        }
        if (isH2) {
            // H2 PostgreSQL mode 兼容转换：
            // - BIGSERIAL → H2 不识别，改为 IDENTITY (SQL 标准)
            // - DATEADD (SQL Server) → INTERVAL (PostgreSQL)
            // - ON CONFLICT DO NOTHING → H2 跳过该语句（种子数据不是 schema 必需）
            sql = sql
                .replace("BIGSERIAL PRIMARY KEY", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
                .replace("BIGSERIAL", "BIGINT GENERATED BY DEFAULT AS IDENTITY")
                .replace("DATEADD('DAY', -60, CURRENT_TIMESTAMP)", "DATEADD('DAY', -60, CURRENT_TIMESTAMP)")  // 保留原写法以防万一
                .replace("CURRENT_TIMESTAMP - INTERVAL '60 days'", "(CURRENT_TIMESTAMP - INTERVAL '60' DAY)")
                .replace("CURRENT_TIMESTAMP - INTERVAL '45 days'", "(CURRENT_TIMESTAMP - INTERVAL '45' DAY)")
                .replace("CURRENT_TIMESTAMP - INTERVAL '35 days'", "(CURRENT_TIMESTAMP - INTERVAL '35' DAY)")
                .replace("CURRENT_TIMESTAMP - INTERVAL '10 days'", "(CURRENT_TIMESTAMP - INTERVAL '10' DAY)")
                .replace("CURRENT_TIMESTAMP - INTERVAL '5 days'", "(CURRENT_TIMESTAMP - INTERVAL '5' DAY)")
            // 去掉 ON CONFLICT 行（H2 PostgreSQL mode 不支持 ON CONFLICT DO NOTHING；
            // 种子数据是可选的，跳过不影响测试）
            sql = sql.lines().filterNot { it.trim().contains("ON CONFLICT") }.joinToString("\n")
        }
        ds.connection.use { conn ->
            conn.createStatement().use { stmt ->
                for (statement in sql.split(";")) {
                    // Strip leading -- comment lines from each statement before executing.
                    // Bug: prior `!trimmed.startsWith("--")` check would skip the FIRST
                    // statement when the SQL file had a leading comment block (e.g.
                    // "schema-h2.sql" starts with 4 comment lines + CREATE TABLE).
                    val cleaned = statement.lines()
                        .filter { !it.trim().startsWith("--") }
                        .joinToString("\n")
                        .trim()
                    if (cleaned.isNotEmpty()) {
                        try {
                            stmt.execute(cleaned)
                        } catch (e: Exception) {
                            log.warn("Schema statement failed (continuing): {}", cleaned.lines().first())
                            log.warn("  Error: {}", e.message)
                            // 继续执行剩余 statements（让 CREATE TABLE 即使某条失败也尝试后续的）
                        }
                    }
                }
            }
        }
        log.info("Database schema initialized successfully")
    }
}